opt_in_rules:
  - colon
  - comma
  - control_statement
  - trailing_newline
  - type_body_length

identifier_name:
  min_length:
    warning: 1
    error: 1

vertical_whitespace:
  max_empty_lines: 1

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - multiple_closures_with_trailing_closure
  - empty_parentheses_with_trailing_closure
  - redundant_optional_initialization
  - unused_optional_binding
  - unneeded_synthesized_initializer

excluded:
  - TodoItemTests
